version: 43.0.9
pageUuid: e4ac775a-964e-11ed-b36e-138237f5b127
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
  queryStatusVisibility: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: false
  rootScreen: null
  version: 2.108.11
  markdownLinkBehavior: auto
  experimentalDataTabEnabled: true
